price_single: '2500'
price_corporate: '50000'
price_associate_lt100: '15000'
price_associate_lt250: '20000'
price_associate_lt500: '25000'
price_associate_lt1m: '30000'
price_associate_gt1m: '40000'
price_full_lt100: '25000'
price_full_lt250: '35000'
price_full_lt500: '37500'
price_full_lt1m: '40000'
price_full_gt1m: '50000'
