mlid:
  'menu_link_content:8e0eaa68-9fc6-43fe-902b-f1c748d2f6e6':
    roles:
      - member
    access_check: false
  'menu_link_content:35708b45-170d-474f-8e71-39f0d09bde63':
    roles:
      - authenticated
    access_check: false
  'menu_link_content:c6b608e8-6b7b-4b43-a087-e07a265100a6':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:387ed7e4-99a7-49fa-8061-06e10466dd77':
    roles:
      - anonymous
    access_check: false
  'menu_link_content:372c0ac5-b546-491d-8d03-5f9dabaa24a7':
    roles: {  }
    access_check: false
  'menu_link_content:33242468-aaad-419b-86d8-77607749dbf8':
    roles: {  }
    access_check: false
  'menu_link_content:557954a2-92c0-46b3-b876-eaf9391c5e56':
    roles: {  }
    access_check: false
  'menu_link_content:22f45c38-8e2c-45ac-bfe0-99ae8b639918':
    roles: {  }
    access_check: false
  'menu_link_content:c78b515e-06fc-4417-8b42-81dadc25e23d':
    roles: {  }
    access_check: false
  'menu_link_content:f5476e7c-9422-48a1-ae34-959d3e0d2caa':
    roles: {  }
    access_check: false
  'menu_link_content:698c72df-d81a-4a64-b896-a7e5603d0f10':
    roles: {  }
    access_check: false
  'menu_link_content:aee63a1c-ff23-4938-a710-3087a821a235':
    roles: {  }
    access_check: false
  'menu_link_content:8815661b-70e2-4270-9d26-89f6d147a385':
    roles: {  }
    access_check: false
  'menu_link_content:c5697a90-be77-4eec-8495-b338720b0c4c':
    roles: {  }
    access_check: false
  'menu_link_content:bc52086e-5858-4eae-9719-52108d48d919':
    roles: {  }
    access_check: false
  'menu_link_content:27ff613c-c87d-4623-a929-1f780fc04b75':
    roles: {  }
    access_check: false
  'menu_link_content:34ee4f20-5918-41cd-8a6b-f551f1238a3e':
    roles: {  }
    access_check: false
