parameters:
  development_environment.var.dump.class: Drupal\development_environment\Service\VarDumpService

services:
  development_environment.var.dump.service:
    class: '%development_environment.var.dump.class%'
